// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcSn1gWMzQiao5gF4cIhbLj48Ulv_FyIo',
    appId: '1:246701362500:android:28fa691fd386e04e001b11',
    messagingSenderId: '246701362500',
    projectId: 'groupie-cf135',
    storageBucket: 'groupie-cf135.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsvIsTdYiR4ikYsqawMwY_P85lOwTIGO8',
    appId: '1:246701362500:ios:db5a73988258fc81001b11',
    messagingSenderId: '246701362500',
    projectId: 'groupie-cf135',
    storageBucket: 'groupie-cf135.appspot.com',
    androidClientId: '246701362500-50nr3dfpfvqss9kog864ab3kjl9528a0.apps.googleusercontent.com',
    iosClientId: '246701362500-eo11knpfgt2bv31l94tfsb5ckc0f7d7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.gropie',
  );
}
